import { Event, Order, Ticket, ScanLog, AdminStats } from '@/types';

export const DEMO_EVENTS: Event[] = [
  {
    id: 'evt-sunburn-arena',
    name: 'Sunburn Arena',
    slug: 'sunburn-arena-ahmedabad',
    venue: 'Sardar Patel Stadium',
    address: 'Navrangpura, Ahmedabad, Gujarat 380009',
    city: 'Ahmedabad',
    mapLink: 'https://maps.google.com/?q=Sardar+Patel+Stadium+Ahmedabad',
    dates: 'Dec 15, 2026',
    startDate: '2026-12-15',
    endDate: '2026-12-15',
    timings: '6:00 PM - 10:00 PM',
    description: 'Experience the ultimate electronic dance music festival with international DJs, spectacular stage design, and premium sound and lighting.',
    artist: 'DJ Snake',
    bannerUrl: '/demo/events/banner_sunburn.jpg',
    organizerId: 'org-1',
    organizerName: 'Sunburn Festival',
    ageRestriction: '18+ only.',
    dressCode: 'Smart Casual.',
    terms: ['Entry is non-transferable.', 'No refund after booking.'],
    status: 'published',
    ticketTypes: [
      { id: 'sp-sun', name: 'General Admission', price: 1499, maxPerBooking: 6, totalInventory: 5000, soldQuantity: 3200, remainingQuantity: 1800, benefits: ['General Area Entry'], status: 'available' },
      { id: 'vp-sun', name: 'VIP Pass', price: 4999, maxPerBooking: 4, totalInventory: 500, soldQuantity: 380, remainingQuantity: 120, benefits: ['VIP Lounge', 'Premium View', 'Dedicated Bar'], status: 'available' },
    ],
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'evt-ahmedabad-royal-garba',
    name: 'Ahmedabad Garba Night',
    slug: 'ahmedabad-garba-night',
    venue: 'GMDC Ground',
    address: '132 Feet Ring Road, Ahmedabad, Gujarat 380052',
    city: 'Ahmedabad',
    mapLink: 'https://maps.google.com/?q=GMDC+Ground+Ahmedabad',
    dates: 'Oct 3 - Oct 12, 2026',
    startDate: '2026-10-03',
    endDate: '2026-10-12',
    timings: '8:00 PM - 12:30 AM',
    description: "Ahmedabad's most premium Navratri night featuring dazzling decorations, live orchestra, and celebrity performances.",
    artist: 'Kinjal Dave',
    bannerUrl: '/demo/events/banner_navratri.jpg',
    organizerId: 'org-2',
    organizerName: 'Royal Events Gujarat',
    ageRestriction: 'All ages welcome.',
    dressCode: 'Traditional attire recommended.',
    terms: ['Valid ID proof mandatory for entry.'],
    status: 'published',
    ticketTypes: [
      { id: 'tt_single', name: 'Single Entry Pass', price: 499, maxPerBooking: 6, totalInventory: 4000, soldQuantity: 2800, remainingQuantity: 1200, benefits: ['General Entry', 'Live Dandiya'], status: 'available' },
      { id: 'tt_couple', name: 'Couple Entry Pass', price: 899, maxPerBooking: 3, totalInventory: 2000, soldQuantity: 1500, remainingQuantity: 500, benefits: ['Entry for 2'], status: 'available' },
      { id: 'tt_vip', name: 'VIP Pass', price: 1499, maxPerBooking: 2, totalInventory: 400, soldQuantity: 350, remainingQuantity: 50, benefits: ['VIP Enclosure', 'Premium Dinner'], status: 'available' },
    ],
    createdAt: '2026-08-05T10:00:00Z',
  },
  {
    id: 'evt-live-music-concert',
    name: 'Live Music Concert',
    slug: 'live-music-concert-surat',
    venue: 'Laxmi Lawns',
    address: 'Dumas Road, Surat, Gujarat 395007',
    city: 'Surat',
    mapLink: 'https://maps.google.com/?q=Laxmi+Lawns+Surat',
    dates: 'Nov 20, 2026',
    startDate: '2026-11-20',
    endDate: '2026-11-20',
    timings: '7:00 PM - 11:00 PM',
    description: "A mesmerizing live music concert featuring the best Bollywood and Indie artists.",
    artist: 'Arijit Singh',
    bannerUrl: '/demo/events/banner_concert.jpg',
    organizerId: 'org-3',
    organizerName: 'Harmony Entertainment',
    ageRestriction: 'Open for all ages.',
    dressCode: 'Smart Casual.',
    terms: ['Entry gates close 1 hour after event starts.'],
    status: 'published',
    ticketTypes: [
      { id: 'sp-sur', name: 'Silver Pass', price: 999, maxPerBooking: 6, totalInventory: 3000, soldQuantity: 1500, remainingQuantity: 1500, benefits: ['Silver Seating'], status: 'available' },
      { id: 'vp-sur', name: 'Gold Pass', price: 2999, maxPerBooking: 4, totalInventory: 300, soldQuantity: 200, remainingQuantity: 100, benefits: ['Front Row Seating', 'Meet & Greet'], status: 'available' },
    ],
    createdAt: '2026-08-10T10:00:00Z',
  },
  {
    id: 'evt-comedy-show',
    name: 'Stand-up Comedy Show',
    slug: 'stand-up-comedy-vadodara',
    venue: 'Sir Sayajirao Auditorium',
    address: 'Kirti Mandir, Vadodara, Gujarat 390001',
    city: 'Vadodara',
    mapLink: 'https://maps.google.com/?q=Sir+Sayajirao+Auditorium+Vadodara',
    dates: 'Jan 10, 2027',
    startDate: '2027-01-10',
    endDate: '2027-01-10',
    timings: '8:00 PM - 10:00 PM',
    description: "Laugh out loud with the best stand-up comedians in the country.",
    artist: 'Zakir Khan',
    bannerUrl: '/demo/events/poster_comedy.jpg',
    organizerId: 'org-4',
    organizerName: 'Laughing Club',
    ageRestriction: '16+ only.',
    dressCode: 'Casual.',
    terms: ['No recording allowed.'],
    status: 'published',
    ticketTypes: [
      { id: 'sp-vad', name: 'Regular Seat', price: 499, maxPerBooking: 6, totalInventory: 800, soldQuantity: 600, remainingQuantity: 200, benefits: ['Balcony Seating'], status: 'available' },
      { id: 'vp-vad', name: 'VIP Seat', price: 1499, maxPerBooking: 4, totalInventory: 100, soldQuantity: 90, remainingQuantity: 10, benefits: ['Front Row Seating'], status: 'available' },
    ],
    createdAt: '2026-08-15T10:00:00Z',
  },
];

export const DEMO_BOOKINGS: Order[] = [
  {
    id: 'BK-20261001-001',
    eventId: 'evt-ahmedabad-royal-garba',
    customerName: 'Rahul Patel',
    mobile: '9876543210',
    email: 'rahul@example.com',
    city: 'Ahmedabad',
    ticketTypes: [{ ticketTypeId: 'tt_single', ticketTypeName: 'Single Entry Pass', quantity: 2, unitPrice: 499, subtotal: 998 }],
    amount: 1038,
    paymentStatus: 'paid',
    ticketCount: 2,
    createdAt: '2026-10-01T14:30:00Z',
  },
  {
    id: 'BK-20261001-002',
    eventId: 'evt-ahmedabad-royal-garba',
    customerName: 'Priya Shah',
    mobile: '9876543211',
    email: 'priya@example.com',
    city: 'Ahmedabad',
    ticketTypes: [{ ticketTypeId: 'tt_vip', ticketTypeName: 'VIP Pass', quantity: 1, unitPrice: 1499, subtotal: 1499 }],
    amount: 1549,
    paymentStatus: 'paid',
    ticketCount: 1,
    createdAt: '2026-10-01T15:00:00Z',
  },
  {
    id: 'BK-20261002-003',
    eventId: 'evt-surat-diamond-dandiya',
    customerName: 'Amit Desai',
    mobile: '9876543212',
    email: 'amit@example.com',
    city: 'Surat',
    ticketTypes: [{ ticketTypeId: 'cp-srt', ticketTypeName: 'Couple Pass', quantity: 2, unitPrice: 699, subtotal: 1398 }],
    amount: 1454,
    paymentStatus: 'paid',
    ticketCount: 2,
    createdAt: '2026-10-02T10:15:00Z',
  },
  {
    id: 'BK-20261002-004',
    eventId: 'evt-vadodara-heritage-raas',
    customerName: 'Sneha Joshi',
    mobile: '9876543213',
    email: 'sneha@example.com',
    city: 'Vadodara',
    ticketTypes: [
      { ticketTypeId: 'sp-vad', ticketTypeName: 'Single Pass', quantity: 3, unitPrice: 349, subtotal: 1047 },
      { ticketTypeId: 'kp-vad', ticketTypeName: 'Kids Pass', quantity: 1, unitPrice: 149, subtotal: 149 },
    ],
    amount: 1244,
    paymentStatus: 'paid',
    ticketCount: 4,
    createdAt: '2026-10-02T18:30:00Z',
  },
  {
    id: 'BK-20261003-005',
    eventId: 'evt-ahmedabad-royal-garba',
    customerName: 'Kiran Mehta',
    mobile: '9876543214',
    email: 'kiran@example.com',
    city: 'Ahmedabad',
    ticketTypes: [{ ticketTypeId: 'ss-ahm', ticketTypeName: 'Season Pass', quantity: 1, unitPrice: 3999, subtotal: 3999 }],
    amount: 4079,
    paymentStatus: 'paid',
    ticketCount: 1,
    createdAt: '2026-10-03T09:00:00Z',
  },
];

export const DEMO_TICKETS: Ticket[] = [
  {
    id: 'PN-AHM-3K81',
    bookingId: 'BK-20261001-001',
    eventId: 'evt-ahmedabad-royal-garba',
    eventName: 'Royal Garba Mahotsav',
    eventDate: 'Oct 3 - Oct 12, 2026',
    venue: 'Sardar Patel Stadium, Ahmedabad',
    customerName: 'Rahul Patel',
    customerPhone: '9876543210',
    passType: 'Single Pass',
    passDate: '2026-10-03',
    status: 'valid',
    secureToken: 'tk_sec_abc123def456ghi789jk',
    isUsed: false,
    entryTime: null,
    scannedBy: null,
    gateName: null,
    createdAt: '2026-10-01T14:30:00Z',
  },
  {
    id: 'PN-AHM-3K82',
    bookingId: 'BK-20261001-001',
    eventId: 'evt-ahmedabad-royal-garba',
    eventName: 'Royal Garba Mahotsav',
    eventDate: 'Oct 3 - Oct 12, 2026',
    venue: 'Sardar Patel Stadium, Ahmedabad',
    customerName: 'Rahul Patel',
    customerPhone: '9876543210',
    passType: 'Single Pass',
    passDate: '2026-10-03',
    status: 'used',
    secureToken: 'tk_sec_ghi789jkl012mno345pq',
    isUsed: true,
    entryTime: '2026-10-03T20:15:00Z',
    scannedBy: 'scanner-1',
    gateName: 'Gate A',
    createdAt: '2026-10-01T14:30:00Z',
  },
  {
    id: 'PN-AHM-9V01',
    bookingId: 'BK-20261001-002',
    eventId: 'evt-ahmedabad-royal-garba',
    eventName: 'Royal Garba Mahotsav',
    eventDate: 'Oct 3 - Oct 12, 2026',
    venue: 'Sardar Patel Stadium, Ahmedabad',
    customerName: 'Priya Shah',
    customerPhone: '9876543211',
    passType: 'VIP Pass',
    passDate: '2026-10-03',
    status: 'valid',
    secureToken: 'tk_sec_mno345pqr678stu901vw',
    isUsed: false,
    entryTime: null,
    scannedBy: null,
    gateName: null,
    createdAt: '2026-10-01T15:00:00Z',
  },
  {
    id: 'PN-SRT-4D11',
    bookingId: 'BK-20261002-003',
    eventId: 'evt-surat-diamond-dandiya',
    eventName: 'Diamond City Dandiya',
    eventDate: 'Oct 3 - Oct 12, 2026',
    venue: 'Laxmi Lawns & Convention, Surat',
    customerName: 'Amit Desai',
    customerPhone: '9876543212',
    passType: 'Couple Pass',
    passDate: '2026-10-03',
    status: 'valid',
    secureToken: 'tk_sec_stu901vwx234yza567bc',
    isUsed: false,
    entryTime: null,
    scannedBy: null,
    gateName: null,
    createdAt: '2026-10-02T10:15:00Z',
  },
  {
    id: 'PN-VAD-7H21',
    bookingId: 'BK-20261002-004',
    eventId: 'evt-vadodara-heritage-raas',
    eventName: 'Heritage Raas Garba',
    eventDate: 'Oct 3 - Oct 12, 2026',
    venue: 'Navlakhi Grounds, Vadodara',
    customerName: 'Sneha Joshi',
    customerPhone: '9876543213',
    passType: 'Single Pass',
    passDate: '2026-10-03',
    status: 'cancelled',
    secureToken: 'tk_sec_yza567bcd890efg123hi',
    isUsed: false,
    entryTime: null,
    scannedBy: null,
    gateName: null,
    createdAt: '2026-10-02T18:30:00Z',
  },
];

export const DEMO_SCAN_LOGS: ScanLog[] = [
  { id: 'scan-1', ticketId: 'PN-AHM-3K82', eventId: 'evt-ahmedabad-royal-garba', result: 'valid', scannedBy: 'scanner-1', scannedAt: '2026-10-03T20:15:00Z', gateName: 'Gate A' },
  { id: 'scan-2', ticketId: 'PN-AHM-3K82', eventId: 'evt-ahmedabad-royal-garba', result: 'already_used', scannedBy: 'scanner-2', scannedAt: '2026-10-03T20:45:00Z', gateName: 'Gate B' },
  { id: 'scan-3', ticketId: 'FAKE-TICKET', eventId: 'evt-ahmedabad-royal-garba', result: 'invalid', scannedBy: 'scanner-1', scannedAt: '2026-10-03T21:00:00Z', gateName: 'Gate A' },
];

export function getDemoAdminStats(): AdminStats {
  const totalTicketsSold = DEMO_EVENTS.reduce((sum, e) => sum + e.ticketTypes.reduce((s, p) => s + p.soldQuantity, 0), 0);
  const totalRevenue = DEMO_BOOKINGS.reduce((sum, b) => sum + b.amount, 0);
  return {
    totalEvents: DEMO_EVENTS.length,
    totalTicketsSold,
    totalRevenue,
    todaySales: 4079,
    totalCustomers: DEMO_BOOKINGS.length,
    totalScans: DEMO_SCAN_LOGS.length,
    successfulEntries: DEMO_SCAN_LOGS.filter(s => s.result === 'valid').length,
    pendingEntries: totalTicketsSold - DEMO_SCAN_LOGS.filter(s => s.result === 'valid').length,
    invalidScans: DEMO_SCAN_LOGS.filter(s => s.result === 'invalid').length,
    duplicateScans: DEMO_SCAN_LOGS.filter(s => s.result === 'already_used').length,
  };
}

export const CITIES = ['All Cities', 'Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Gandhinagar'];
