'use client';

import { useState } from 'react';
import { Play, RotateCcw, CheckCircle, ExternalLink, Loader2, Database } from 'lucide-react';
import toast from 'react-hot-toast';
import Link from 'next/link';

export default function SystemTest() {
  const [loadingSetup, setLoadingSetup] = useState(false);
  const [loadingReset, setLoadingReset] = useState(false);

  const handleSetup = async () => {
    setLoadingSetup(true);
    try {
      const res = await fetch('/api/admin/demo-setup', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'create' })
      });
      const data = await res.json();
      if (res.ok && data.success) {
        toast.success('Demo environment seeded successfully');
      } else {
        toast.error('Failed to setup demo');
      }
    } catch (error) {
      toast.error('Network error');
    } finally {
      setLoadingSetup(false);
    }
  };

  const handleReset = async () => {
    if (!confirm('Are you sure you want to delete all demo orders, tickets and checkins?')) return;
    setLoadingReset(true);
    try {
      const res = await fetch('/api/admin/demo-setup', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'reset' })
      });
      const data = await res.json();
      if (res.ok && data.success) {
        toast.success('Demo data reset successfully');
      } else {
        toast.error('Failed to reset demo data');
      }
    } catch (error) {
      toast.error('Network error');
    } finally {
      setLoadingReset(false);
    }
  };

  return (
    <div className="p-6 lg:p-10 max-w-4xl mx-auto space-y-8 pb-20 bg-[#F7F7F8] min-h-screen">
      <div>
        <h1 className="text-3xl font-[900] tracking-tight text-[#111111]">End-to-End System Test</h1>
        <p className="text-gray-500 font-[500] mt-1 text-sm">Validate the full RaasPass platform flow securely using the Demo Mode.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="bg-white rounded-[1.5rem] p-6 border border-gray-100 shadow-[0_4px_20px_rgb(0,0,0,0.03)] flex flex-col items-start gap-4">
          <div className="w-12 h-12 bg-blue-50 rounded-xl flex items-center justify-center">
            <Database className="w-6 h-6 text-blue-600" />
          </div>
          <div>
            <h2 className="text-lg font-[800] text-[#111111]">1. Create Demo Setup</h2>
            <p className="text-xs text-gray-500 font-[500] mt-1">Seeds "RaasPass Demo Garba Night", Demo Organizer, and Scanner Staff into Firestore.</p>
          </div>
          <button 
            onClick={handleSetup}
            disabled={loadingSetup}
            className="w-full bg-[#111111] text-white px-5 py-3 rounded-xl font-[800] text-sm shadow-md hover:bg-gray-900 transition-all flex justify-center items-center gap-2 mt-auto disabled:opacity-70"
          >
            {loadingSetup ? <Loader2 className="w-4 h-4 animate-spin" /> : <Play className="w-4 h-4" />}
            Seed Demo Environment
          </button>
        </div>

        <div className="bg-white rounded-[1.5rem] p-6 border border-gray-100 shadow-[0_4px_20px_rgb(0,0,0,0.03)] flex flex-col items-start gap-4">
          <div className="w-12 h-12 bg-red-50 rounded-xl flex items-center justify-center">
            <RotateCcw className="w-6 h-6 text-[#E53935]" />
          </div>
          <div>
            <h2 className="text-lg font-[800] text-[#111111]">Reset Demo Data</h2>
            <p className="text-xs text-gray-500 font-[500] mt-1">Deletes orders, tickets, and check-ins generated by the demo event. Resets inventory.</p>
          </div>
          <button 
            onClick={handleReset}
            disabled={loadingReset}
            className="w-full bg-white border border-gray-200 text-[#E53935] px-5 py-3 rounded-xl font-[800] text-sm shadow-sm hover:bg-red-50 transition-all flex justify-center items-center gap-2 mt-auto disabled:opacity-70"
          >
            {loadingReset ? <Loader2 className="w-4 h-4 animate-spin" /> : <RotateCcw className="w-4 h-4" />}
            Reset Demo Data
          </button>
        </div>
      </div>

      <div className="bg-white rounded-[1.5rem] border border-gray-100 shadow-[0_4px_20px_rgb(0,0,0,0.03)] overflow-hidden">
        <div className="p-5 bg-gray-50/50 border-b border-gray-100">
          <h2 className="text-lg font-[800] text-[#111111]">Testing Quick Links</h2>
        </div>
        <div className="p-2 flex flex-col">
          <Link href="/events/raaspass-demo-garba-night" target="_blank" className="flex items-center justify-between p-4 hover:bg-gray-50 rounded-xl transition-colors">
            <span className="font-[600] text-sm text-[#111111]">Open Public Demo Event</span>
            <ExternalLink className="w-4 h-4 text-gray-400" />
          </Link>
          <Link href="/my-tickets" target="_blank" className="flex items-center justify-between p-4 hover:bg-gray-50 rounded-xl transition-colors border-t border-gray-50">
            <span className="font-[600] text-sm text-[#111111]">Open My Tickets</span>
            <ExternalLink className="w-4 h-4 text-gray-400" />
          </Link>
          <Link href="/scan/login" target="_blank" className="flex items-center justify-between p-4 hover:bg-gray-50 rounded-xl transition-colors border-t border-gray-50">
            <span className="font-[600] text-sm text-[#111111]">Open Scanner App</span>
            <ExternalLink className="w-4 h-4 text-gray-400" />
          </Link>
          <Link href="/organizer/login" target="_blank" className="flex items-center justify-between p-4 hover:bg-gray-50 rounded-xl transition-colors border-t border-gray-50">
            <span className="font-[600] text-sm text-[#111111]">Open Organizer Portal</span>
            <ExternalLink className="w-4 h-4 text-gray-400" />
          </Link>
        </div>
      </div>
    </div>
  );
}
